### ISSUE TITLE
please help me solve some questions when i use phyCLIP.

### ISSUE THREAD

**Issue by Guojiahuii** [alvinxhan/PhyCLIP#1]
![1](https://user-images.githubusercontent.com/52458219/60557948-f8115580-9d79-11e9-86ab-7ba712dbb7b2.png)
![2](https://user-images.githubusercontent.com/52458219/60557950-f8a9ec00-9d79-11e9-9fb4-7a3b20d74afe.png)
when i run the example data by phyCLIP, i always meet two questions. please give me some advices to solve two questions.
thank u very much!

**Comment by alvinxhan** [comment]
Hi, apologies for not replying sooner. Do you mind attaching your input tree file for me to determine the source of the error? Thanks!

**Comment by Guojiahuii** [comment]
> Hi, apologies for not replying sooner. Do you mind attaching your input tree file for me to determine the source of the error? Thanks!

Hi，I am sorry for replying late. i use the example file as input tree file. And I don't know if it's a problem with my installation method. apologies for  replying late again！Thank u very much!
